#!name=Locket Gold 🏅- abcducanh
#!desc=Mở khoá premium + Badge cho ứng dụng Locket Widget
# 🚀 Rewrite by: abcducanh

[General]
user-agent = Locket/1.0.0 (iPhone; iOS 26.3; Scale/3.00)

[Script]
# RevenueCat - Gold
revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.*\/(receipts$|subscribers\/[^/]+$), script-path=https://raw.githubusercontent.com/abcducanh/hihi/main/locketfix3.js, requires-body=true, max-size=-1, timeout=120

# Locket API - Badge
locket-api = type=http-response, pattern=^https:\/\/api\.locketcamera\.com\/, script-path=https://raw.githubusercontent.com/abcducanh/hihi/main/locketfix3.js, requires-body=true, max-size=-1, timeout=120

# Xóa headers RevenueCat
deleteHeader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.*\/(receipts|subscribers), script-path=https://raw.githubusercontent.com/abcducanh/hihi/main/header2.js, timeout=120

# Xóa headers Locket
deleteHeaderLocket = type=http-request, pattern=^https:\/\/api\.locketcamera\.com\/, script-path=https://raw.githubusercontent.com/abcducanh/hihi/main/header2.js, timeout=60

[MITM]
hostname = api.revenuecat.com, *.revenuecat.com, api.locketcamera.com
enable = true
ssl-pinning = false
ca-pinned = false
