#!name=Locket Gold 🏅- NightmarketServer v5
#!desc=Mở khoá premium + huy hiệu + icon + theme

[General]
user-agent = Locket/1.0.0 (iPhone; iOS 26.3; Scale/3.00)
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local
dns-server = 8.8.8.8, 1.1.1.1
ipv6-v4 = false
tls-session-cache = true

[Script]
# RevenueCat - main
revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/v1\/(subscribers|receipts), script-path=https://raw.githubusercontent.com/NightmarketServer/Locket/main/locketfix3.js, requires-body=true, max-size=-1, timeout=120

# RevenueCat - backup
revenuecat-backup = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.*, script-path=https://raw.githubusercontent.com/NightmarketServer/Locket/main/locketfix3.js, requires-body=true, max-size=-1, timeout=120

# Locket API - bắt domain chính
locket-api = type=http-response, pattern=^https:\/\/api\.locketcamera\.com\/.*, script-path=https://raw.githubusercontent.com/NightmarketServer/Locket/main/locketfix3.js, requires-body=true, max-size=-1, timeout=120

# Badge - bắt mọi request có chữ badge
badge-all = type=http-response, pattern=badge, script-path=https://raw.githubusercontent.com/NightmarketServer/Locket/main/locketfix3.js, requires-body=true, max-size=-1, timeout=120

# Strip headers - RevenueCat
strip-headers = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.*, script-path=https://raw.githubusercontent.com/NightmarketServer/Locket/main/header2.js, timeout=60

# Strip headers - Locket API
strip-headers2 = type=http-request, pattern=^https:\/\/api\.locketcamera\.com\/.*, script-path=https://raw.githubusercontent.com/NightmarketServer/Locket/main/header2.js, timeout=60

[MITM]
hostname = api.revenuecat.com, *.revenuecat.com, api.locketcamera.com, raw.githubusercontent.com
enable = true
ssl-pinning = false
ca-pinned = false
